apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: web-rs
spec:
  replicas: 8
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-ctr
        image: nigelpoulton/k8sbook:latest
        ports:
        - containerport: 8080

